BAPHY_CONFIG_PATH='abcng';
WIN_SERVER_PATH='M:\';
MAC_SERVER_PATH='/Volumes/data/';
LINUX_SERVER_PATH='/auto/data/';
% DB_SERVER='129.199.80.89';
DB_SERVER='129.199.82.245';
DB_USER='admin';
DB_PASSWORD='feartheferret';
