function [Data,HeaderStruct] = evpread5(filename)

fid = fopen(filename);
if fid<=0 error(['File ',escapeMasker(filename),' could not be opened.']); end
EVPVersion = fread(fid,1,'uint32'); 
if EVPVersion~=5 error('wrong evp version'); end

headerLength = fread(fid,1,'uint32');
Header = [EVPVersion,headerLength,fread(fid,headerLength-2,'double')'];
HeaderStruct = struct('EVPVersion',Header(1),...
  'HeaderLength',Header(2),...
  'DateNum',Header(3),...
  'InputRange',Header([4,5]),...
  'int16factor',Header(6),...
  'SR',Header(7),...
  'BoardNum',Header(8),...
  'ChannelNum',Header(9));

Data = single(fread(fid,inf,'int16'))/HeaderStruct.int16factor;
fclose(fid);