function o = TextureMorphing(varargin)
% TextureMorphing produces a morphing between cloud of tones drawn from 2
% different distributions
%
% Yves 2013

% Initial Set of Trials (for the moment: Bernhard):
% Index selects between 20 Indices
% 4 Pitchclasses for the Biasing Region
% 5 Randomizations
% 24 TestPitches
% 10 Repetitions
%
% Length of each presentation 5*24*0.15 = 18s


switch nargin
  case 0  % if no input arguments, create a default object
      
    Fields = {...
      'MorphingCategory','popupmenu','none',...%|MovingLimit',...     
      'D1shape','popupmenu','uniform',...%|normal|cauchy',...
      'D1param','edit','2.2',...
      'D2shape_KeepTails','popupmenu','none',...%|offset_normal|normal|none',...     
      'D2param_KeepTails','edit','2.2',...    % when increased, less peaky
      'D2shape_KeepBody','popupmenu','almost_uniform',...%|normal|offset_normal|cauchy|none',...     
      'D2param_KeepBody','edit','2.2',...
      'DifficultyLvl_KeepBody','edit',' 50 80 110 140',...      % decreasing difficulty
      'DifficultyLvl_KeepTails','edit','50 80 110 140',...    % decreasing difficulty
      'Inverse_D1D2','popupmenu','no',...    %|yes',...   
      'MinToC','edit','0',...   
      'MaxToC','edit','8',... 
      'MorphingDuration','edit','0',...
      'FrozenPatternsAdress','popupmenu','C:\Users\Booth1\Dropbox\FrozenPatterns',... %'C:\Code\baphy\UtilitiesYves\FrozenPatterns',... %, ...'C:\Users\Yves\Dropbox\ABCng\FrozenPatterns',
      'FrozenPatternsNb','edit','0'};      

%     Fields = {...
%       'MorphingCategory','popupmenu','none',...   %|MovingLimit',...     
%       'D1shape','popupmenu','shuffle_normal',...          %|normal|cauchy|offset_normal_smooth_tails,...      
%       'D1param','edit',['0.58 , 2.2 , 0.15 ,' num2str(round(rand(1,1)*100))],...  %'D1param','edit','0.58 , 2.2',...
%       'D2shape_KeepTails','popupmenu','none',...        %       'D2shape_KeepTails','popupmenu','cauchy',...%|offset_normal|normal|none',...
%       'D2param_KeepTails','edit','0',...               %       'D2param_KeepTails','edit','.32',...    % when increased, less peaky
%       'D2shape_KeepBody','popupmenu','shuffle_normal',...  %       'D2shape_KeepBody','popupmenu','offset_normal_smooth_tails',...%|normal|offset_normal|cauchy|none',...
%       'D2param_KeepBody','edit',['0.58 , 2.2 , 0.15 ,' num2str(round(rand(1,1)*100))],...                      %       'D2param_KeepBody','edit','0.58 , 2.2',...
%       'DifficultyLvl_KeepBody','edit','3 , 6 , 8 , 11',...      % decreasing difficulty
%       'DifficultyLvl_KeepTails','edit','3 , 6 , 8 , 11',...    % decreasing difficulty
%       'Inverse_D1D2','popupmenu','yes',...    %|no',...   
%       'MinToC','edit','0',...   
%       'MaxToC','edit','8',... 
%       'MorphingDuration','edit','0',...
%       'FrozenPatternsAdress','popupmenu','/home/yves/Dropbox/ABCng/FrozenPatterns', ...'C:\Users\Yves\Dropbox\ABCng\FrozenPatterns',
%       'FrozenPatternsNb','edit','16'};      
             
%     Fields = {...
%       'MorphingCategory','popupmenu','none',...   %|MovingLimit',...
%       'D1shape','popupmenu','creneau_normal',...          %|normal|cauchy|offset_normal_smooth_tails,...      
%       'D1param','edit','0.58 , 2.2 , 0.2 , 1 , 0.25',...  %'D1param','edit','0.58 , 2.2',...
%       'D2shape_KeepTails','popupmenu','none',...        %       'D2shape_KeepTails','popupmenu','cauchy',...%|offset_normal|normal|none',...
%       'D2param_KeepTails','edit','0',...               %       'D2param_KeepTails','edit','.32',...    % when increased, less peaky
%       'D2shape_KeepBody','popupmenu','creneau_normal',...  %       'D2shape_KeepBody','popupmenu','offset_normal_smooth_tails',...%|normal|offset_normal|cauchy|none',...
%       'D2param_KeepBody','edit','0.58 , 2.2 , 0.2 , -1 , 0.25',...                      %       'D2param_KeepBody','edit','0.58 , 2.2',...
%       'DifficultyLvl_KeepBody','edit','76 , 58 , 43 , 13',...      % decreasing difficulty
%       'DifficultyLvl_KeepTails','edit','58 , 48 , 38 , 22 ',...    % decreasing difficulty
%       'Inverse_D1D2','popupmenu','yes',...    %|no',...   
%       'MinToC','edit','0',...   
%       'MaxToC','edit','8',... 
%       'MorphingDuration','edit','0',...
%       'FrozenPatternsAdress','popupmenu','/home/yves/Dropbox/ABCng/FrozenPatterns', ...'C:\Users\Yves\Dropbox\ABCng\FrozenPatterns',
%       'FrozenPatternsNb','edit','16'};

%     Fields = {...
%       'MorphingCategory','popupmenu','ClampedLimit',...%|MovingLimit',...     
%       'D1shape','popupmenu','offset_normal_smooth_tails',...%|normal|cauchy',...
%       'D1param','edit','0.58 , 2.2',...
%       'D2shape_KeepTails','popupmenu','cauchy',...%|offset_normal|normal|none',...     
%       'D2param_KeepTails','edit','.32',...    % when increased, less peaky
%       'D2shape_KeepBody','popupmenu','offset_normal_smooth_tails',...%|normal|offset_normal|cauchy|none',...     
%       'D2param_KeepBody','edit','0.58 , 2.2',...
%       'DifficultyLvl_KeepBody','edit','76 , 58 , 43 , 13',...      % decreasing difficulty
%       'DifficultyLvl_KeepTails','edit','58 , 48 , 38 , 22 ',...    % decreasing difficulty
%       'Inverse_D1D2','popupmenu','yes',...    %|no',...   
%       'MinToC','edit','0',...   
%       'MaxToC','edit','8',... 
%       'MorphingDuration','edit','0',...
%       'FrozenPatternsAdress','popupmenu','C:\Code\baphy\UtilitiesYves\FrozenPatterns',... %'/home/yves/Dropbox/ABCng/FrozenPatterns', ...'C:\Users\Yves\Dropbox\ABCng\FrozenPatterns',
%       'FrozenPatternsNb','edit','16'};
      
%       'MorphingCategory','popupmenu','MovingLimit',...%|MovingLimit',...     
%       'D1shape','popupmenu','offset_normal',...%|normal|cauchy',...
%       'D1param','edit','0.58 , 2.2',...
%       'D2shape_KeepTails','popupmenu','cauchy',...%|offset_normal|normal|none',...     
%       'D2param_KeepTails','edit','0.075',...  
%       'D2shape_KeepBody','popupmenu','normal',...%|offset_normal|cauchy|none',...     
%       'D2param_KeepBody','edit','0.7',... 
%       'DifficultyLvl_KeepTails','edit','5 , 6.5 , 8 , 9.5',...
%       'DifficultyLvl_KeepBody','edit','3.5 , 6.5 , 12.5 , 21.5',...
  
  
    s = SoundObject ('TextureMorphing', 44100, 0,0.4, 0, {''}, 1, Fields);
    for i=1:length(Fields)/3; o.(Fields{(i-1)*3+1}) = Fields{i*3}; end
    o.Fields = Fields;
    o.FieldNames = Fields(1:3:end-2); 
    o.FieldTypes = Fields(2:3:end-1);
    o.MaxIndex = 0;
    o.RunClass = 'TMG'; o.Duration = NaN;

    
    o.FrequencySpace = []; o.XDistri = []; o.F0 = [];
    o.D1 = []; o.D2_KeepTails = []; o.MergedD_KeepTails = []; o.D2_KeepBody = []; o.MergedD_KeepBody = [];  
    o.IniSeed = [];
    o.MorphingTypeByInd = []; o.DifficultyLvlByInd = []; o.ReverseByInd = [];
    o.AllTargetPositions = []; o.CurrentTargetPositions = [];
    
    o.Names = {};
    o.Ranges = {}; o.VarFieldNames = {};  o.VarFieldInds = []; o.Par = [];    o = class(o,'TextureMorphing',s);
    o = ObjUpdate(o);
  case 1 % if single argument of class SoundObject, return it
    if isa(varargin{1},'SoundObject')   s = varargin{1};
    else        error('Wrong argument type');     end
  otherwise error('Wrong number of input arguments');
end
