mex('-v','-Ic:\Program Files\IVI Foundation\IVI\Include',...
    '-Ic:\Program Files\IVI Foundation\Visa\Win64\Include',...
    '-IC:\Program Files (x86)\IVI Foundation\VISA\WinNT\include',...
    '-Lc:\Program Files\IVI Foundation\IVI\Bin',...
    '-L.\',...
    '-lniHSDIO',...
    'hsdio_test.c');