set(0,'defaultAxesFontName', 'Times')
set(0,'defaultTextFontName', 'Times')
FontSize = 25;
set(0,'defaultAxesFontSize', FontSize)
set(0,'defaultTextFontSize', FontSize)
set(0,'defaultTextFontSize', FontSize)
set(0,'defaultTextFontSize', FontSize)
set(0,'defaultlinelinewidth',1.5)
set(0,'defaultaxeslinewidth',1.2)
set(0,'defaultpatchlinewidth',1.2)