set(0,'defaultAxesFontName', 'Times')
set(0,'defaultTextFontName', 'Times')
set(0,'defaultAxesFontSize', 15)
set(0,'defaultTextFontSize', 15)
set(0,'defaultTextFontSize', 15)
set(0,'defaultTextFontSize', 15)
set(0,'defaultlinelinewidth',1.15)
set(0,'defaultaxeslinewidth',1.15)
set(0,'defaultpatchlinewidth',1.15)